# ==========================================================================
# QuickMQ 百万连接 ulimit 配置
# 使用方法: sudo cp limits.conf /etc/security/limits.d/99-quickmq.conf
# 重新登录或重启服务生效
# ==========================================================================

# 进程文件描述符上限
*    soft    nofile    1500000
*    hard    nofile    1500000

# 进程数限制
*    soft    nproc     65535
*    hard    nproc     65535
